### ISSUE TITLE
reading trajectory

### ISSUE THREAD

**Issue by ahmadubuntu** [AlexGabourie/thermo#13]
Dear Alex

If the box coordinates will be in integer, the code gives error!

```
ITEM: TIMESTEP
4990000
ITEM: NUMBER OF ATOMS
77664
ITEM: BOX BOUNDS pp pp pp
-86.1 86.1
-85.2169 85.2169
-19 200
```

In this example, the Thermo (thermo/lammps/data.py) code couldn't read the zdata.

**Comment by AlexGabourie** [comment]
Thank you for bringing this to my attention. I'm assuming the function in question is `get_sim_dimensions()`? I'll try to update this as soon as I can.

**Comment by ahmadubuntu** [comment]
It's my pleasure.

I think there is no need for line 53 of the data.py:
                            area.append(xwidth*ywidth)
because the Xwidth and Ywidth are not defined yet. 


Best wishes.

**Comment by AlexGabourie** [comment]
Since much of the LAMMPS code has not been updated for some time, I decided to rewrite this function entirely. Please try the new function and let me know if it works for you. Note that some of the _syntax has been changed_. The function name was shortened to `get_dimensions` and the new output keys and input arguments are described [here](https://thermomd.readthedocs.io/en/latest/thermo.lammps.html#thermo.lammps.data.get_dimensions)

**Comment by AlexGabourie** [comment]
I will close this issue for now. Please let me know if I need to reopen it.
